### ISSUE TITLE
Changes to the darknet makefile can cause for the install script to fail

### ISSUE THREAD

**Issue by drew-neely** [bennetthardwick/darknet.js#11]
2 days ago the owner of the darknet repository pushed a change to the makefile in which he changed `OPENCV=0` to `OPENCV=1`. For those of us that do not have OpenCV installed and configured, npm install does not work. Adding the following lines to install-script.sh lines fixes the problem.
```
sed -i -e "s/OPENCV=[01]/OPENCV=0/g" ./Makefile
sed -i -e "s/OPENMP=[01]/OPENMP=0/g" ./Makefile
```
It would be nice for this library to add the options for compiling with OpenCV and OpenMP in the same way that it has the options to compile with GPU and CUDNN.

**Comment by bennetthardwick** [comment]
At the moment we support OpenCV through opencv4nodejs, but some time in the future I want to start using Darknet's version. Probably in the next university break.
