### ISSUE TITLE
Is possible to limit classes to detect? 

### ISSUE THREAD

**Issue by Animion** [bennetthardwick/darknet.js#13]
To speedup detection is possible to configure classes to detect?

**Comment by bennetthardwick** [comment]
Unfortunately no. The only way that you could limit the amount of classes to detect and get a speed boost, would be to train a new model that only has those classes. If you're interested in doing this, have a look [here](https://pjreddie.com/darknet/yolo/). This library uses [pjreddie's darknet](https://github.com/pjreddie/darknet) under the hood, so it's limited only by what it can do.
