### ISSUE TITLE
cant assign gpu and cudnn

### ISSUE THREAD

**Issue by sumanth512** [bennetthardwick/darknet.js#17]
I cant enable gpu and cudnn.when I tried to export cudnn and gpu it show me 'fatal: destination path 'darknet' already exists and is not an empty directory.' this error

**Comment by bennetthardwick** [comment]
Hi @sumanth512, I can't seem to reproduce this issue. Can you list the steps you took to cause this issue? The darknet install process is a bit finicky, running the script below might fix your issue:
```
rm -rf node_modules/darknet
export DARKNET_BUILD_WITH_GPU=1
export DARKNET_BUILD_WITH_CUDNN=1
npm install darknet
```
