### ISSUE TITLE
box is off

### ISSUE THREAD

**Issue by TadaWasRaped** [bennetthardwick/darknet.js#31]
The values the wrapper is returning differs from what happens when I run the same weights directly off darknet

**Comment by bennetthardwick** [comment]
Hey thanks for the issue! Since this wrapper and the darknet CLI set the detections up a bit differently, there's always going to be some differences. How off is it?

**Comment by TadaWasRaped** [comment]
About 100px on X and Y axis and a little bit on width https://imgur.com/a/0t83CT0

**Comment by nparziale** [comment]
I think the x and y on a detection are the box center, try to rest half the width to x and half the height to y.

**Comment by TadaWasRaped** [comment]
> I think the x and y on a detection are the box center, try to rest half the width to x and half the height to y.

Oh I didn't even notice its centered thanks
