### ISSUE TITLE
DARKNET_BUILD_WITH_OPENMNP no longer honored. 

### ISSUE THREAD

**Issue by vajonam** [bennetthardwick/darknet.js#34]
There is typo here  in the install-script.sh

```
OOPENMPPENMP="${DARKNET_BUILD_WITH_OPENMP:-0}";
```

should be ```OPENMP="${DARKNET_BUILD_WITH_OPENMP:-0}";```

**Comment by bennetthardwick** [comment]
Thanks! I've put out 3.0.3 - hopefully, it fixes this.

**Comment by vajonam** [comment]
Yeah working now.. that alexyab fork is such a noisy compile :-)
