### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by clement200** [bennetthardwick/darknet.js#39]
This wrapper works brilliantly but seems to eat up my computers ram under prolonged use.
I can't seem to find where this problem is coming from but it looks like the memory used by the images never seems to be released to the OS. 
Am I the only one encountering this problem?

**Comment by bennetthardwick** [comment]
Hey thanks for opening an issue, what method are you using for your detections? Is it `detectImagePath` or `detectImageBuffer`?

**Comment by clement200** [comment]
I'm using detectImageBuffer as I'm passing a opencv imread to darknet.detect.

**Comment by bennetthardwick** [comment]
Turns out I was doing some dodgy stuff when creating the image - I'ved fixed it in b896ad6 and published. Can you try `darknet@3.0.5` and let me know whether that's fixed it for you?

**Comment by clement200** [comment]
Thanks! I had a look at the fix and modified detector.cpp accordingly and rebuilt darknet@3.0.3 and it seems to have fixed it!
On another note, I can't seem to compile darknet successfully:
On v3.0.4 I get:
> ./install-script.sh: line 53: DARKNET_BUILD_WITH_ARCH : parameter not defined

On v3.0.5 I get: 
> nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

I modify the makefile to add the extra ARCH anyway before rebuilding v3.0.3 and it works perfectly for me.

**Comment by bennetthardwick** [comment]
There were some errors in the install script (:facepalm:) - can you try `darknet@3.0.6` and see if that works for you?

**Comment by clement200** [comment]
Just tried it and it seems to compile and work perfectly!  Thanks for the quick fixes!
